/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos/index'
import { Route as AuthenticatedKitsIndexRouteImport } from './routes/_authenticated/kits/index'
import { Route as AuthenticatedAnunciosIndexRouteImport } from './routes/_authenticated/anuncios/index'
import { Route as AuthenticatedProdutosNovoRouteImport } from './routes/_authenticated/produtos/novo'
import { Route as AuthenticatedKitsNovoRouteImport } from './routes/_authenticated/kits/novo'
import { Route as AuthenticatedAnunciosNovoRouteImport } from './routes/_authenticated/anuncios/novo'
import { Route as AuthenticatedProdutosIdEditarRouteImport } from './routes/_authenticated/produtos/$id.editar'
import { Route as AuthenticatedKitsIdEditarRouteImport } from './routes/_authenticated/kits/$id.editar'
import { Route as AuthenticatedAnunciosIdEditarRouteImport } from './routes/_authenticated/anuncios/$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKitsIndexRoute = AuthenticatedKitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnunciosIndexRoute =
  AuthenticatedAnunciosIndexRouteImport.update({
    id: '/anuncios/',
    path: '/anuncios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosNovoRoute =
  AuthenticatedProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKitsNovoRoute = AuthenticatedKitsNovoRouteImport.update({
  id: '/kits/novo',
  path: '/kits/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnunciosNovoRoute =
  AuthenticatedAnunciosNovoRouteImport.update({
    id: '/anuncios/novo',
    path: '/anuncios/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIdEditarRoute =
  AuthenticatedProdutosIdEditarRouteImport.update({
    id: '/produtos/$id/editar',
    path: '/produtos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKitsIdEditarRoute =
  AuthenticatedKitsIdEditarRouteImport.update({
    id: '/kits/$id/editar',
    path: '/kits/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnunciosIdEditarRoute =
  AuthenticatedAnunciosIdEditarRouteImport.update({
    id: '/anuncios/$id/editar',
    path: '/anuncios/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api': typeof AuthenticatedApiRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/callback': typeof ApiCallbackRoute
  '/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/kits/novo': typeof AuthenticatedKitsNovoRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/anuncios/': typeof AuthenticatedAnunciosIndexRoute
  '/kits/': typeof AuthenticatedKitsIndexRoute
  '/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/anuncios/$id/editar': typeof AuthenticatedAnunciosIdEditarRoute
  '/kits/$id/editar': typeof AuthenticatedKitsIdEditarRoute
  '/produtos/$id/editar': typeof AuthenticatedProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api': typeof AuthenticatedApiRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/callback': typeof ApiCallbackRoute
  '/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/kits/novo': typeof AuthenticatedKitsNovoRoute
  '/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/anuncios': typeof AuthenticatedAnunciosIndexRoute
  '/kits': typeof AuthenticatedKitsIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/anuncios/$id/editar': typeof AuthenticatedAnunciosIdEditarRoute
  '/kits/$id/editar': typeof AuthenticatedKitsIdEditarRoute
  '/produtos/$id/editar': typeof AuthenticatedProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/api/callback': typeof ApiCallbackRoute
  '/_authenticated/anuncios/novo': typeof AuthenticatedAnunciosNovoRoute
  '/_authenticated/kits/novo': typeof AuthenticatedKitsNovoRoute
  '/_authenticated/produtos/novo': typeof AuthenticatedProdutosNovoRoute
  '/_authenticated/anuncios/': typeof AuthenticatedAnunciosIndexRoute
  '/_authenticated/kits/': typeof AuthenticatedKitsIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/anuncios/$id/editar': typeof AuthenticatedAnunciosIdEditarRoute
  '/_authenticated/kits/$id/editar': typeof AuthenticatedKitsIdEditarRoute
  '/_authenticated/produtos/$id/editar': typeof AuthenticatedProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/metricas'
    | '/vendas'
    | '/api/callback'
    | '/anuncios/novo'
    | '/kits/novo'
    | '/produtos/novo'
    | '/anuncios/'
    | '/kits/'
    | '/produtos/'
    | '/anuncios/$id/editar'
    | '/kits/$id/editar'
    | '/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/metricas'
    | '/vendas'
    | '/api/callback'
    | '/anuncios/novo'
    | '/kits/novo'
    | '/produtos/novo'
    | '/anuncios'
    | '/kits'
    | '/produtos'
    | '/anuncios/$id/editar'
    | '/kits/$id/editar'
    | '/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/api'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fornecedores'
    | '/_authenticated/metricas'
    | '/_authenticated/vendas'
    | '/api/callback'
    | '/_authenticated/anuncios/novo'
    | '/_authenticated/kits/novo'
    | '/_authenticated/produtos/novo'
    | '/_authenticated/anuncios/'
    | '/_authenticated/kits/'
    | '/_authenticated/produtos/'
    | '/_authenticated/anuncios/$id/editar'
    | '/_authenticated/kits/$id/editar'
    | '/_authenticated/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kits/': {
      id: '/_authenticated/kits/'
      path: '/kits'
      fullPath: '/kits/'
      preLoaderRoute: typeof AuthenticatedKitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/': {
      id: '/_authenticated/anuncios/'
      path: '/anuncios'
      fullPath: '/anuncios/'
      preLoaderRoute: typeof AuthenticatedAnunciosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/novo': {
      id: '/_authenticated/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/produtos/novo'
      preLoaderRoute: typeof AuthenticatedProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kits/novo': {
      id: '/_authenticated/kits/novo'
      path: '/kits/novo'
      fullPath: '/kits/novo'
      preLoaderRoute: typeof AuthenticatedKitsNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/novo': {
      id: '/_authenticated/anuncios/novo'
      path: '/anuncios/novo'
      fullPath: '/anuncios/novo'
      preLoaderRoute: typeof AuthenticatedAnunciosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$id/editar': {
      id: '/_authenticated/produtos/$id/editar'
      path: '/produtos/$id/editar'
      fullPath: '/produtos/$id/editar'
      preLoaderRoute: typeof AuthenticatedProdutosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kits/$id/editar': {
      id: '/_authenticated/kits/$id/editar'
      path: '/kits/$id/editar'
      fullPath: '/kits/$id/editar'
      preLoaderRoute: typeof AuthenticatedKitsIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anuncios/$id/editar': {
      id: '/_authenticated/anuncios/$id/editar'
      path: '/anuncios/$id/editar'
      fullPath: '/anuncios/$id/editar'
      preLoaderRoute: typeof AuthenticatedAnunciosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedAnunciosNovoRoute: typeof AuthenticatedAnunciosNovoRoute
  AuthenticatedKitsNovoRoute: typeof AuthenticatedKitsNovoRoute
  AuthenticatedProdutosNovoRoute: typeof AuthenticatedProdutosNovoRoute
  AuthenticatedAnunciosIndexRoute: typeof AuthenticatedAnunciosIndexRoute
  AuthenticatedKitsIndexRoute: typeof AuthenticatedKitsIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedAnunciosIdEditarRoute: typeof AuthenticatedAnunciosIdEditarRoute
  AuthenticatedKitsIdEditarRoute: typeof AuthenticatedKitsIdEditarRoute
  AuthenticatedProdutosIdEditarRoute: typeof AuthenticatedProdutosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedAnunciosNovoRoute: AuthenticatedAnunciosNovoRoute,
  AuthenticatedKitsNovoRoute: AuthenticatedKitsNovoRoute,
  AuthenticatedProdutosNovoRoute: AuthenticatedProdutosNovoRoute,
  AuthenticatedAnunciosIndexRoute: AuthenticatedAnunciosIndexRoute,
  AuthenticatedKitsIndexRoute: AuthenticatedKitsIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedAnunciosIdEditarRoute: AuthenticatedAnunciosIdEditarRoute,
  AuthenticatedKitsIdEditarRoute: AuthenticatedKitsIdEditarRoute,
  AuthenticatedProdutosIdEditarRoute: AuthenticatedProdutosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCallbackRoute: ApiCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
